export { normalize, stripRanges } from './normalize.js'
export { normalizeCharacters } from './normalize-characters.js'
export { fingerprint } from './fingerprint.js'
export { stripDiacritics, isDiacritic } from './diacritics.js'
export { stripZeroWidth } from './zero-width.js'
export { normalizeAlif } from './alif.js'
export { normalizeHamza } from './hamza.js'
export { normalizeNumerals, toUrduNumerals, fromUrduNumerals } from './numerals.js'
export { removeKashida } from './kashida.js'
export { normalizePresentationForms } from './presentation.js'
export { DIACRITIC_RANGES, HONORIFIC_RANGES, ALIF_VARIANTS, PRESENTATION_FORMS_MAP } from './unicode-data.js'
